compressionLevel: 0

enableGlobalCache: true

logFilters:
  - code: YN0005
    level: discard
  - code: YN0076
    level: discard
  - level: discard
    pattern: '@workspace:addons/storyshots-*'

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: ../.yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: ../.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

unsafeHttpWhitelist:
  - localhost

# TODO: improve perf here by switching to yannPath
yarnPath: ../.yarn/releases/yarn-3.4.1.cjs
installStatePath: '../.yarn/scripts-install-state.gz'
