on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]

name: Danger JS
jobs:
  dangerJS:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: Danger JS
        uses: danger/danger-js@11.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --dangerfile scripts/dangerfile.ts
