name: Release

on:
  push:
    branches:
      - main
      - new-next
      - release-*

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: ${{ contains(github.event.head_commit.message, 'Version Packages') && 'release' || '' }}
    steps:
      - run: echo ${{ github.event.head_commit.message }}
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/berry/cache
          key: yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-
            yarn-v1-

      - name: Install Dependencies
        run: yarn task --task install --start-from never --no-link --debug

      - name: Create 'Version Packages' Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn publish:changesets
          cwd: code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
